package com.nonomartinez.sfc.cofradiasapi.hermandad.model;

public enum Dias {
    VIERNES_DOLORES, SABADO_PASION, DOMINGO_DE_RAMOS, LUNES_SANTO, MARTES_SANTO, MIERCOLES_SANTO, JUEVES_SANTO, VIERNES_SANTO_MADRUGA, VIERNES_SANTO, SABADO_SANTO, DOMINGO_RESURRECCION
}
